Upgrade to Qt 6.8
flathub/org.shotcut.Shotcut pull request #120
Opened 2024-10-31 04:00 UTC by hfiguiere

2024-10-31 04:00 UTC, hfiguiere commented
The app starts. I haven't done more extensive testing.

2024-10-31 19:32 UTC, ddennedy requested changes
Please do not merge this until I agree to it.

2024-11-21 19:29 UTC, ddennedy commented
I just started testing with Qt 6.8, and the plan is to upgrade to it here and some other builds for next release in January 2025

2025-01-10 21:08 UTC, ddennedy commented
Closing as this is in the beta branch, which is going well and on schedule to merge to release by then end of January.

2025-01-10 21:08 UTC, closed without merging